- name: Import API proxy
  env:
    ORG: ${{ secrets.APIGEE_ORG }}
    ENV: ${{ secrets.APIGEE_ENV }}
  run: |
    echo "Getting token..."
    TOKEN=$(gcloud auth print-access-token)

    echo "Importing proxy..."
    apigeecli apis import \
      -b demoapi.zip \
      -o $ORG \
      -t $TOKEN
